version: 2
updates:
  - package-ecosystem: npm
    assignees:
      - stfsy
    directory: /
    schedule:
      interval: monthly
    ignore:
      - dependency-name: chai
    versioning-strategy: increase

  - package-ecosystem: github-actions
    assignees:
      - stfsy
    directory: /
    schedule:
      interval: monthly
